[project]
name = "2-langraf-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "ipython>=9.10.0",
    "langgraph>=1.0.8",
    "typing>=3.10.0.0",
]
